export ZDOTDIR=$HOME/.config/zsh
HISTFILE=$HOME/.config/zsh/.zsh_history
setopt appendhistory

# Add slash at end of directories
setopt no_auto_remove_slash

# Expand characters like tilde
setopt extendedglob
setopt nomatch
setopt menucomplete

# Disable beep
unsetopt BEEP

# Colors
autoload -Uz colors && colors

# Useful Functions
source "$ZDOTDIR/zsh-functions"

# Normal files to source
zsh_add_file "zsh-aliases"
zsh_add_file "zsh-prompt"

# Plugins
zsh_add_plugin "zsh-users/zsh-autosuggestions"
zsh_add_plugin "zsh-users/zsh-syntax-highlighting"

# Path variable.
PATH=/usr/local/bin:/usr/local/sbin:~/bin:/usr/local/opt/openjdk/bin:/usr/local/bin/node:/usr/local/opt/ruby/bin:/usr/local/opt/openjdk/bin:/usr/local/bin/npm:/usr/local/bin/latexmk:/usr/local/texlive/2021/bin/universal-darwin:$PATH
export PATH
