-- ls.add_snippets("lua",
-- {
--     s("req",
--     {
--         t("local "),
--         i(1, "arg"),
--         t(" = require(\""),
--         rep(1),
--         t("\")"),
--         i(0),
--     },
--     {
--         condition = conds.line_begin,
--     }),
-- },
-- {
--     type = "autosnippets",
--     key = "all_auto",
-- })
--
--
-- ls.add_snippets("rust",
-- {
--     s(
--         "allow",
--         fmt(
--         [[
--             #![allow({})]{}
--         ]],
--         {
--             i(1, "args"),
--             i(0),
--         }
--         )
--     ),
--
--     s(
--         "allowduu",
--         fmt(
--         [[
--             #![allow(dead_code, unused_imports, unused_variables)]{}
--         ]],
--         { i(0) }
--         )
--     ),
--
--     s(
--         "derive",
--         fmt(
--         [[
--             #[derive({})]{}
--         ]],
--         {
--             i(1, "args"),
--             i(0),
--         }
--         )
--     ),
--
--     s(
--         "derivedebug",
--         fmt(
--         [[
--             #[derive(Debug)]{}
--         ]],
--         { i(0) }
--         )
--     ),
--
--     s(
--         "assert",
--         fmt(
--         [[
--             assert_eq!({}, {});{}
--         ]],
--         { i(1, "left"), i(2, "right"), i(0) }
--         )
--     ),
-- },
-- {}
-- )
