local Plugin = { "folke/noice.nvim" }

-- Plugin.event = "VeryLazy"
--
-- function Plugin.init()
--     vim.keymap.set({ "i", "n", "s" }, "<C-d>", function()
--         if not require("noice.lsp").scroll(4) then
--             return "<C-d>"
--         end
--     end, { silent = true, expr = true })
--     vim.keymap.set({ "i", "n", "s" }, "<C-u>", function()
--         if not require("noice.lsp").scroll(-4) then
--             return "<C-u>"
--         end
--     end, { silent = true, expr = true })
-- end
--
-- function Plugin.config()
--     require("noice").setup({
--         cmdline = {
--             enabled = true,
--             view = "cmdline_popup",
--             -- cmdline = { pattern = "^:", icon = "", lang = "vim" },
--             -- search_down = { kind = "search", pattern = "^/", icon = " ", lang = "regex" },
--             -- search_up = { kind = "search", pattern = "^%?", icon = " ", lang = "regex" },
--             -- filter = { pattern = "^:%s*!", icon = "$", lang = "bash" },
--             -- lua = { pattern = { "^:%s*lua%s+", "^:%s*lua%s*=%s*", "^:%s*=%s*" }, icon = "", lang = "lua" },
--             -- help = { pattern = "^:%s*he?l?p?%s+", icon = "" },
--         },
--         lsp = {
--             progress = {
--                 enabled = false,
--             },
--             override = {
--                 ["vim.lsp.util.convert_input_to_markdown_lines"] = true,
--                 ["vim.lsp.util.stylize_markdown"] = true,
--                 ["cmp.entry.get_documentation"] = true,
--             },
--         },
--         -- You can enable a preset for easier configuration
--         presets = {
--             bottom_search = false,        -- use a classic bottom cmdline for search
--             command_palette = true,       -- position the cmdline and popupmenu together
--             long_message_to_split = true, -- long messages will be sent to a split
--             inc_rename = false,           -- enables an input dialog for inc-rename.nvim
--             lsp_doc_border = true,        -- add a border to hover docs and signature help
--         },
--     })
-- end

return Plugin
